### ISSUE TITLE
Support multiple accounts per domain

### ISSUE THREAD

**Issue by A8795876** [languitar/pass-git-helper#1]
This is really useful, I've been having trouble using netrc with multiple accounts,
not to mention the cleartext issue.

The helper doesn't consider the common case of having multiple accounts per domain.
I have several github accounts for example.

I suggest you add support for this as well as explicitly setting a default fallback account,
as well as a default account.

Naming scheme:
1. `<server>/<username>` - named account (0,1 or more of these)
1. `<server> `single user name for server - (optional) default account to be used if no named account exists. 

The user can undefined `2` to enforce a policy in which all remotes must be defined with a username, i.e. `https://foobar@github.com/foobar/foo` for pass to be used, or else git prompts for credentials (which Is what I'd like).

**Comment by languitar** [comment]
In the config file the domain is matched against the whole URL. So you could add rules based on the complete URL to a specific github project to associate a certain password store entry with a certain github project. Does this solve your issue?

**Comment by languitar** [comment]
Oh no, I am wrong. The git request doesn't event send me the requested path on the server despite what is said in the API documentation: https://www.kernel.org/pub/software/scm/git/docs/git-credential.html

**Comment by languitar** [comment]
You need to set `credential.useHttpPath = true` in your git config. Afterwards the whole path is used for searching now. Does this help?

**Comment by A8795876** [comment]
That'll work,  Thanks!
