### ISSUE TITLE
[feature request] Allow matching based on current working directory

### ISSUE THREAD

**Issue by mstarodub** [languitar/pass-git-helper#12]
When using ssh-based authentication, matching of the keys is done according to the system's ssh config, which, like pass-git-helper, works on a URL basis.

But the authentication credentials are not the only thing that matters in a multiple user context - the entries for username and email in .gitconfig need to be adjusted as well. 

Conveniently, git supports the `includeif` statement in `.gitconfig` starting with 2.13. With that, the username, email and correct ssh keys can be set up to be selected based on the current working directory - for the ssh keys, this is done with 
```
[url "git@github.com-USERNAME"]
  insteadOf = git@github.com
``` 
See [this gist](https://gist.github.com/yinzara/bbedc35798df0495a4fdd27857bca2c1) for a more detailed explanation on this kind of setup.

Now, when working with repos with a mix of both ssh and https origin, this becomes unintuitive, as pass-git-helper only supports matching based on the URL, which is tedious and gives you less options. Perhaps a command line argument could be passed to toggle matching on the current folder instead?

**Comment by languitar** [comment]
you can specify a different mapping file with the `-m` option. Is that sufficient use the per-folder configuration of git?

**Comment by mstarodub** [comment]
Maybe I am missing something, but matching would still be done on the remote URL. For using the per-folder configuration, matching on the current folder would be needed.

**Comment by languitar** [comment]
Can't you reconfigure the call to `pass-git-helper` such that a specific mapping file is used per folder?

**Comment by mstarodub** [comment]
I'm sorry, I didn't understand what you meant at first. I did not think of this, it works as flawlessly. Thanks a lot!

**Comment by languitar** [comment]
Great to hear!

**Comment by languitar** [comment]
Once this works for you, could you open a pull request with some explanations of the use case in the README file of this repo? That would help other users.

**Comment by mstarodub** [comment]
An attempt was made in #13. It turned out to be a bit convoluted due to the amount of configuration files involved.
