### ISSUE TITLE
Do not working with username?

### ISSUE THREAD

**Issue by huipengcheng** [languitar/pass-git-helper#125]
If I only set the password in the store database, `git push` will ask me for username and pass-git-helper will automatically fill the password for me.
But if I set both password and username in the database, `git push` will show the message below:

```
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/*/*.git'
```

What should I do let pass-git-helper automatically fill both username and password for me and avoid this error?

**Comment by languitar** [comment]
This problem is probably unrelated to this helper. Github has deprecated password authentication two years ago: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/. You need to switch to an access token instead and store this in your password store.

However, the best option for services supporting this is probably to switch to an SSH key for authentication: https://docs.github.com/en/authentication/connecting-to-github-with-ssh

**Comment by languitar** [comment]
I am not sure on Github's requirements for whether a username needs to be present when using a token. You could try the following things manually on the command line and see which version works:

```
git clone https://<token>@github.com/your/private/repo.git
git clone https://<user>:<token>@github.com/your/private/repo.git
```

**Comment by huipengcheng** [comment]
I appreciate for that, thanks for your time.

**Comment by languitar** [comment]
So out of curiosity: is the username allowed with your token or is that the reason for receiving the error?

**Comment by huipengcheng** [comment]
My English may not be good so that you don't understand what I mean.

I'll try to make things clear, when I do `git push`:
- If only **token** stored in `pass`
  - `git` will ask for my username. After I input my username, `pass-git-helper` will fill the **token** for me.
- If both **username** and **token** stored in `pass` with correct format
  - `git` will show me that error message and stop me push

**Comment by huipengcheng** [comment]
So yeah, the username with the token is the reason for receiving the error.

**Comment by grbll** [comment]
I have the same issue as described above.

`git pull` with username + token manually **works**
`git pull` with username manually and token in pass database **works**
`git pull` with username + token in pass database does **not work**

To me this seems to be an issue of the helper, or gits protocol for helpers (maybe we should check if other helpers have similar problems).

**Comment by languitar** [comment]
If you are using one of the fine-grained access tokens, then I think you are supposed to use "oauth2" as the username: https://stackoverflow.com/a/74532853/283649

**Comment by grbll** [comment]
> If you are using one of the fine-grained access tokens, then I think you are supposed to use "oauth2" as the username: https://stackoverflow.com/a/74532853/283649

This worked!
