### ISSUE TITLE
Passing username via configuration directly?

### ISSUE THREAD

**Issue by tfurf** [languitar/pass-git-helper#15]
Looking at the README and code, am I correct in that there isn't currently a way to pass username directly from the `git-pass-mappinig.ini`?

For example,

```ini
[github.com*]
target=software/development/github
username=tfurf
```

If that understanding is correct, would a PR be welcome to add such functionality?

**Comment by languitar** [comment]
A PR would be welcome, but personally I would avoid such a layout. Most tools have agreed on using another line in the password file prefixed with `username: ` to pass in the username, which is supported already.

**Comment by Konfekt** [comment]
By what is configurable through wildcards, a user has to use the same password to use the same username on different servers. To account for a user that uses the same usernames but with different passwords on different servers (as is best practice) how about an option `username` in the `[DEFAULT]` section?

**Comment by languitar** [comment]
You can easily use (the quite established) layout like the following one to reuse the same username for different services:

```
dev/github.com:
---------------
<somepass>
username: languitar

dev/bitbucket.org:
------------------
<somepass>
username: languitar
```

This way, your entries would also be compatible with (browserpass)[https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/] and other common tools based on pass. If we were to include the username only in the mapping for pass-git-helper, other tools couldn't use this additional information.

My general aim for this project was to only store credential information in the password entries themselves and not in the mapping file to avoid duplicating and spreading such information across different places/

**Comment by tfurf** [comment]
I was a bit reluctant to go this way, but succumbed in the end. It makes sense, from separation of concerns, 'do one thing', etc. I'm happy to close (and don't intend to submit a PR).

**Comment by languitar** [comment]
Alright, I'll close this for now.
