### ISSUE TITLE
"Invalid username or password"

### ISSUE THREAD

**Issue by uneven-shiver** [languitar/pass-git-helper#16]
Hello. Whenever I do anything like `pass git push -u --all`, it gives me this output, and I'm somewhat sure it doesn't interpret the username and/or the password correctly.

Output: (with debug logging)
```DEBUG:root:Received request "['protocol=https\n', 'host=github.com\n']"
DEBUG:root:Received action get with request:
{'protocol': 'https', 'host': 'github.com'}
DEBUG:root:Parsing mapping file. Command line: None
DEBUG:root:Parsing mapping file /home/void/.config/pass-git-helper/git-pass-mapping.ini
DEBUG:root:Received request "{'protocol': 'https', 'host': 'github.com'}"
DEBUG:root:Iterating mapping to match against host "github.com"
DEBUG:root:Section "github.com" matches requested host "github.com"
DEBUG:root:Requesting entry "github" from pass
DEBUG:root:Received request "['protocol=https\n', 'host=github.com\n', 'username=└── uneven-shiver\n', 'password=github\n']"
DEBUG:root:Received action erase with request:
{'protocol': 'https', 'host': 'github.com', 'username': '└── uneven-shiver', 'password': 'github'}
DEBUG:root:Parsing mapping file. Command line: None
DEBUG:root:Parsing mapping file /home/void/.config/pass-git-helper/git-pass-mapping.ini
INFO:root:Action erase is currently not supported
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/uneven-shiver/<insert repo>.git/'
```

No matter what I try to change in the config file, I simply can't get this to work. I have my password file in the way pass expects it, password first and then user. 

Here's my config:
```ini
[github.com]
target=github
username_extractor=specific_line
line_username=1
```

and here's my `pass show github` output:
```
github
└── uneven-shiver
```

Is there a bug in the program itself or did I do my config wrong? 

Thank you for your attention.
-- Stefan

**Comment by languitar** [comment]
What is strange here is that the username includes the line art at the beginning:
```
DEBUG:root:Received request "['protocol=https\n', 'host=github.com\n', 'username=` uneven-shiver\n', 'password=github\n']"
```
This will probably result in the credentials being invalid and that's also the reason why git then triggers an erase call, which is rejected because it is not supported. I am not exactly sure how this line art `└──` gets into your username.

**Comment by languitar** [comment]
Oh, now I see it. `target` must be the complete path to a single record. So in your case it should be `github/uneven-shiver`.

**Comment by uneven-shiver** [comment]
Indeed, that solved the problem. Thank you so much.
