### ISSUE TITLE
Configuration suggestions

### ISSUE THREAD

**Issue by paddy-hack** [languitar/pass-git-helper#172]
First of all, thanks for this :heart: 

I just want to make two suggestions for integrating this helper.

In my `.config/git/config` I use
``` ini
[credential]
  # Check the cache first and fall back to pass-git-helper if that is
  # available.
  helper = cache
  helper = !type pass-git-helper >/dev/null && pass-git-helper$@
```
so I can share this file across machines independent of the presence of `pass-git-helper`.

My `.config/pass-git-helper/git-pass-mapping.ini` looks like
``` ini
# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: © 2022 Olaf Meeuwissen

[DEFAULT]
  # Use a browserpass compatible regular expression to search for a user
  # account name.  The value to use must be in the *first* capture.  The
  # regex uses ?i: and ?: to achieve this, case insensitively.
  username_extractor = regex_search
  regex_username = ^(?i:(?:user(?:name)?|login)): (.*)$

[*]
  # Find all password files by host name.  Per host symlinks can be used
  # in case account information is kept in a file matching the domain.
  target = ${host}
```
so I can use any of the username fields that [browserpass](https://github.com/browserpass/browserpass-extension) recognizes and don't have to set an explicit `target` for sites.  It enough to add a hostname matching symlink to my password store.

Hope this helps!

**Comment by languitar** [comment]
Thanks for the suggestions. Would you mind opening a PR with updates to the readme to incorporate these ideas?
