### ISSUE TITLE
Error when using through ssh

### ISSUE THREAD

**Issue by lervag** [languitar/pass-git-helper#18]
When I use this through `ssh` I get the following error message:

```
gpg: decryption failed: No secret key
warning: invalid credential line: 1
Traceback (most recent call last):
  File "/usr/bin/pass-git-helper", line 11, in <module>
    load_entry_point('pass-git-helper==1.1.0', 'console_scripts', 'pass-git-helper')()
  File "/usr/lib/python3.8/site-packages/passgithelper.py", line 431, in main
    get_password(request, mapping)
  File "/usr/lib/python3.8/site-packages/passgithelper.py", line 371, in get_password
    output = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pass', 'show', 'sintef/overleaf']' returned non-zero exit status 2.
```

I assume this is because `pass` will through `gpg-agent` try to get the password from `stdin`, and that this is currently not supported by `pass-git-helper`?

Would it be possible to somehow allow text input of the master password?

**Comment by languitar** [comment]
Yes, there is no easy way around this and this is also [documented in the preconditions](https://github.com/languitar/pass-git-helper#preconditions). As Git is already using stdin and out for communicating with the credential helper, I don't see a way to interactively ask for the passphrase at that point in time.

You have two options to work around this:

1. Use ssh agent forwarding (`ssh -A`) to use the SSH agent your own computer for unlocking the store, under the assumption that the key is present there as well.
2. Before using the first interaction with pass, start an SSH agent in your remote session and add the key via `ssh-add`. As long as you are within the configured timeout of the agent, no passphrase has to be acquired anymore than.

**Comment by lervag** [comment]
Thanks. I remember having read something about it, but I missed it when skimming the README file earlier today.

As I'm quite new to the use of `gpg` and `gpg-agent` (and currently, I've only used it to initialize and setup `pass` itself), I am glad for all tips on how to use it properly.

I see you deleted the last part of your  answer, to which I was going to ask how I can "combine" ssh agents with the gpg agent...

**Comment by languitar** [comment]
Took the wrong turn there. That was the other agent thing ;-)

I'll have a look if I can find some trickery to connect std in and out...

**Comment by languitar** [comment]
Hm, weird, now that I try this at home with `pinentry-curses`, everything works as expected. What pinentry-program is configured on your remote host?

**Comment by lervag** [comment]
> Hm, weird, now that I try this at home with pinentry-curses, everything works as expected. What pinentry-program is configured on your remote host?

What do you mean "expected"? Do you mean that `git pull` works, or that you can retrieve passwords first as a workaround?

Note, if I run `pass show ...` in my terminal first for caching the master password, then the `pinentry-curses` is run and the next `git` command works. So this works as a workaround.

**Comment by languitar** [comment]
> What do you mean "expected"? Do you mean that `git pull` works, or that you can retrieve passwords first as a workaround?

I was successfully asked for the password via pinentry-curses while doing the first `git pull`.

**Comment by lervag** [comment]
Hmm, that's strange. This does not happen for me. Below I've added some possibly relevant context. Do you have any idea what can be the reason it does not work for me?

The relevant git config:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://git.overleaf.com/5e183d522fe15000016b9709
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[credential]
	helper = /usr/bin/pass-git-helper
```

The `~/.gnupg/gpg-agent.conf` for specifying the pinentry program:

```
pinentry-program /usr/bin/pinentry-curses
```

Version of `pass-git-helper`: 1.1

Git version: 2.26.2

**Comment by languitar** [comment]
The only difference that I see (apart from versions) is that I am using the shell invocation syntax:
```
    helper = !/home/languitar/src/pass-git-helper/passgithelper.py $@
```
Can you try that?

**Comment by lervag** [comment]
Huh, strange. I copied the `passgithelper.py` script from `/usr/lib/python3.8/site-packages/passgithelper.py` to `/home/lervag/passgithelper` and then tried to use a similar syntax. I get the same error as before. :\

**Comment by lervag** [comment]
I forgot to supply the `.ini` file, which looks like this:

```ini
[DEFAULT]
username_extractor=regex_search
regex_username=^login: (.*)$

[git.overleaf.com]
target=...
```

**Comment by lervag** [comment]
If you know anything else I could try to "debug" this, let me know. It would be very nice to identify the reason this does not work as expected.

If we can't figure it out, then so be it. The workaround of running `pass show ...` first to cache the master password does work and only implies a minor inconvenience.

**Comment by languitar** [comment]
I'll try to have a closer look within the next days. In any case, I did not intend to support this use case in the beginning as I couldn't get this working when I implemented pass-git-helper. However, now that this suddenly worked in my case, I'll try to have another look at what might be causing this.

**Comment by languitar** [comment]
Sorry, this took a lot longer than I wanted to... One more question: do you use plan SSH keys or do you use GPG for SSH authentication?

**Comment by lervag** [comment]
I use plain SSH keys (`ssh-keygen`, `ssh-copy-id`, etc).

**Comment by languitar** [comment]
Alright, let's try to replicate my setup on you side, just to be sure. Please try the following git config:

```
[credential]
    helper = !/home/languitar/src/pass-git-helper/passgithelper.py -l $@
```
With an appropriate path. `-l` will add some debug logging but has the potential to log confidential information. Please use some test account if possible.

Moreover, please use the following `gpg-agent.conf` on the server side:
```
pinentry-program /usr/bin/pinentry-curses
```

Before testing anything, please use:
```
killall gpg-agent dirmngr gpg
```
to be sure that a fresh gpg-agent is used.

What does happen now, if you do some `git clone https://...`?

**Comment by lervag** [comment]
The output is now:

```
> git pull
DEBUG:root:Received request "['protocol=https\n', 'host=git.overleaf.com\n']"
DEBUG:root:Received action get with request:
{'protocol': 'https', 'host': 'git.overleaf.com'}
DEBUG:root:Parsing mapping file. Command line: None
DEBUG:root:Parsing mapping file /home/lervag/.config/pass-git-helper/git-pass-mapping.ini
DEBUG:root:Received request "{'protocol': 'https', 'host': 'git.overleaf.com'}"
DEBUG:root:Iterating mapping to match against host "git.overleaf.com"
DEBUG:root:Section "git.overleaf.com" matches requested host "git.overleaf.com"
DEBUG:root:Requesting entry "overleaf" from pass
gpg: decryption failed: No secret key
Traceback (most recent call last):
  File "/usr/bin/pass-git-helper", line 11, in <module>
    load_entry_point('pass-git-helper==1.1.0', 'console_scripts', 'pass-git-helper')()
  File "/usr/lib/python3.8/site-packages/passgithelper.py", line 429, in main
    get_password(request, mapping)
  File "/usr/lib/python3.8/site-packages/passgithelper.py", line 371, in get_password
    output = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pass', 'show', 'overleaf']' returned non-zero exit status 2.
Username for 'https://git.overleaf.com':
```

So, I think everything is fine until "Requesting entry ... from pass".

**Comment by languitar** [comment]
so weird. Which distro and version is running on the server?

Btw, maybe [GPG agent forwarding](https://wiki.gnupg.org/AgentForwarding) is running on the remote host?

**Comment by lervag** [comment]
Note, though: When I do `pass show ...`, I _do_ get the curses interface for entering the gpg pass key.

**Comment by lervag** [comment]
Update: `pass show ...` seems to work with the curses interface even without the option in `gpg-agent.conf`.

**Comment by languitar** [comment]
> Note, though: When I do `pass show ...`, I _do_ get the curses interface for entering the gpg pass key.

This is somehow related to the output redirection that is necessary to get the output from `pass show` in the script. But I don't see, why this works on my machine and not on yours.

**Comment by lervag** [comment]
I'm on Arch Linux (both server and client). I don't think I'm using any agent forwarding. I _am_ doing a `ProxyJump` to access my server, though, but I would not think that should matter?

**Comment by lervag** [comment]
I'm looking in the code, and it seems the output I show you is stopping here:

```python
     def get_password(request, mapping) -> None:
         # ...
372              output = subprocess.check_output(["pass", "show", pass_target]).
373              decode(
374                  "utf-8"
375              )
376              lines = output.splitlines()
```

So, it seems the `subprocess.check_output` does not grant "interactivity" to `pass show`...

**Comment by lervag** [comment]
Ok, so I tested the code in a python repl, and there it does seem to work (even on the server through ssh).

**Comment by languitar** [comment]
I think I know why it works in my case. Please try this before running the git operation:
```
export GPG_TTY=$(tty)
```

**Comment by lervag** [comment]
Ah, yes, that does fix things. But why is that necessary? In particular, why is it necessary with your code when it works in my minimal python repl that I just showed?

**Comment by languitar** [comment]
I think the original problem is not my redirection, but the one that git does when communicating with passgithelper via stdin and stdout.

**Comment by languitar** [comment]
Btw, from [the gpg agent documentation](https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html)

> You should always add the following lines to your .bashrc or whatever initialization file is used for all shell invocations: 
> ```
> GPG_TTY=$(tty)
> export GPG_TTY
> ```

**Comment by lervag** [comment]
> Btw, from [the gpg agent documentation](https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html)
> 
> > You should always add the following lines to your .bashrc or whatever initialization file is used for all shell invocations:
> > ```
> > GPG_TTY=$(tty)
> > export GPG_TTY
> > ```

Thanks! With this and your update to the README file in #18, I think this issue is resolved.
