### ISSUE TITLE
git not using the helper defined in the global .gitconfig

### ISSUE THREAD

**Issue by adigitoleo** [languitar/pass-git-helper#180]
I have a strange issue where `pass-git-helper` works if I do something like:

```
echo "protocol=ssh\nhost=github.com\npath=myusername/myrepo.git"|pass-git-helper get
```

but when I set `git config --global credential.helper '!pass-git-helper $@'` and do a `git push` I still get prompted for my ssh key passphrase instead of my GPG master key passphrase. I can't figure it out so I'm wondering if you might be able to help, even though it doesn't seem to be strictly the fault of this script.

Environment info:
```
OS: Void Linux x86_64
Kernel: 6.0.8_1
Shell: zsh 5.9
pass-git-helper: 1.2.0
git: 2.38.1
openssh: 9.1p1
openssl: 1.1.1s
gpg: 2.3.8
```

I tried running `git push -vvv` with the helper set to `!pass-git-helper -l $@` but there is no output, it seems like git is skipping the helper completely for some reason. Using either `pass-git-helper get` or `git credential fill` on the command line with mock stdin that should match what git would give works fine (and when I add the `-l` I can see the debug output). I would like to use this helper mostly for pushing, mostly via SSH. I have set the `GPG_TTY` env var as instructed in the README to use cli pinentry. There is no local git config file. I'm just not sure how I can find out where it is going wrong inside the git machinery. I also tried setting the helper to the full path of the `pass-git-helper` script, but got the same result.

Not sure if it's something you can help with but I thought I'd see if you know anything more about this. Cheers

**Comment by adigitoleo** [comment]
Quick update:
- Tried cloning a private repo via HTTPS, the helper seems to have worked there since I got to the pinentry prompt (clone failed afterwards because password auth is not supported anymore). Could it mean that credential helpers are only possible over HTTPS?
- I forgot to mention that I have my git config set up to always push over SSH:
  ```
  [url "git@github.com:"]
      pushInsteadOf = "https://github.com"
  ```
  If it should work over SSH, maybe that is causing havoc.

**Comment by adigitoleo** [comment]
OK I think I figured out that for SSH, password pgrograms must be configured using `SSH_ASKPASS` instead. Unfortunately it only works for graphical pinentry programs but that's the only option. I'll resort to `pass -c ...` followed by `git push`. Sorry for the noise.

**Comment by languitar** [comment]
The helper is only intended for (legacy) HTTP access to repositories. It will no work for other protocols.
