### ISSUE TITLE
Use passage instead of pass

### ISSUE THREAD

**Issue by gautaz** [languitar/pass-git-helper#193]
Hello,

As [passage](https://github.com/FiloSottile/passage) is a fork of [pass](http://www.passwordstore.org/), is there a simple way to use `pass-git-helper` with `passage` instead of `pass`?

I guess a simple alias would do the trick but perhaps doing this might go wrong so I am basically asking for previous attempts feedback or from people well versed in how `pass-git-helper` works :pray:.

**Comment by languitar** [comment]
If it uses the same binary name, then it should just work. Otherwise, a PR adding a command line argument to override the default binary name would be needed here.

**Comment by gautaz** [comment]
Thanks @languitar for your quick answer, I will most probably operate the transition this weekend (by aliasing `passage` to `pass`).
If it works out of the box, I will close the issue with some details.
If it doesn't, I'll try to provide a PR.

**Comment by gautaz** [comment]
Just tried replacing `pass` with `passage` (I am using NixOS so I basically had to link `pass` to `passage` somewhere in my PATH), it seems to work pretty well, I did not see any glitch for now (fetch/push worked on both github and my employer's git host).

I am closing this issue for now, if a use case fails, I think it will be better to open a new issue with the specifics of this particular use case.
