### ISSUE TITLE
Convert config files to XDG standard

### ISSUE THREAD

**Issue by A8795876** [languitar/pass-git-helper#2]
dotfiles are usually named in a way that suggests the program they are used by.
`pass-git-helper` and `.git-pass-mapping ` aren't really suggestive of one another.

**Comment by languitar** [comment]
I'd rather think this should be ported to xdg conventions. Then we could have `~/.local/share/pass-git-helper/mapping.ini` or the like.

**Comment by languitar** [comment]
Or better `~/.config/pass-git-helper/mapping.ini`
