### ISSUE TITLE
Using multiple github accounts

### ISSUE THREAD

**Issue by jwmwalrus** [languitar/pass-git-helper#21]
Hi.

I have two github accounts, and I'm failing at trying to make pass-git-helper work with both of them.

On pass I have the following layout
```bash
$ pass dev/github.com/
dev/github.com
├── workaccount
└── jwmwalrus
```

On .gitconfig I have
```ini
[includeIf "gitdir:~/workspace/work/"]
 	path = ~/.gitconfig.d/work.gitconfig
[includeIf "gitdir:~/workspace/src/"]
 	path = ~/.gitconfig.d/src.gitconfig
[credential]
    helper = /usr/bin/pass-git-helper -m ~/.config/pass-git-helper/git-pass-mapping.ini
```

And on the mapping file I have:
```ini
[github.com]
target=dev/github.com/${username}
```

When I try to clone as repository from either account, I get an error about `dev/github.com/${username}` not being matched.

If I try moving the `[credentials]` section into the specific `*.gitconfig` and use a mapping with the exact match, i.e.:
```ini
[github.com]
target=dev/github.com/jwmwalrus
```

Then I get an error, because the username line is taken as a whole ---e.g., it's taking `username=username: jwmwalrus` instead of `username=jwmwalrus`.

The only way this second approach seems to work is if I remove the `username: ` prefix from the pass file, e.g.:

````bash
<some-password>
jwmwalrus
email: example@example.org
url: example.org
```

From the documentation, I get that's not the expected usage. Or am I wrong?

**Comment by languitar** [comment]
You should have two different mapping files for pass-git-helper per account, each of them working individually with all required settings, for instance, to strip usernames. Then, the following lines should go into `work.gitconfig` and `src.gitconfig`, each time pointing to the appropriate mapping file:
```
[credential]
    helper = /usr/bin/pass-git-helper -m ~/.config/pass-git-helper/git-pass-mapping.ini
```

For configuring how to extract the username, you can follow [these instructions from the readme](https://github.com/languitar/pass-git-helper#username). The appropriate configuration need to be present in both mapping files.

**Comment by jwmwalrus** [comment]
Hi.

Thank you for answering. It's much clearer now.

Although, the documentation gives the impression that thre "username=" prefix is handled automatically ---which clearly is not.

Thanks again.

**Comment by languitar** [comment]
> Although, the documentation gives the impression that thre "username=" prefix is handled automatically ---which clearly is not.

Which part of the readme gave that impression? Maybe that can be improved then.

**Comment by languitar** [comment]
I'll close this for now. In case you have some information on what lacks in the readme, please reopen this.

**Comment by jwmwalrus** [comment]
Hi.

Sorry for the late reply.

Following the documentation, I had added the following at the top of the (helper's) config file:
```ini
[DEFAULT]
username_extractor=regex_search
regex_username=^Username: (.*)$
```

But that doesn't seem to do anything. In fact, the regex extractor doesn't work even in a specific section.

Only using `username_extractor=specific_line` on the actual `[github.com]` section seems to do anything in terms of skipping characters ---but the `line_username` value is ignored, and the second line (i.e., first line after the password) is always used.

**Comment by languitar** [comment]
> But that doesn't seem to do anything. In fact, the regex extractor doesn't work even in a specific section.

That sounds strange. I have a test case for the `regex_search` mechanism: https://github.com/languitar/pass-git-helper/blob/master/test_data/regex-extraction/git-pass-mapping.ini An example similar to this one give the whole line as the password? Or nothing?

**Comment by jwmwalrus** [comment]
Hi.

Having the following in my helper's config
```ini
[DEFAULT]
username_extractor=regex_search
regex_username=^Username: (.*)$

[github.com]
target=dev/github.com/jwmwalrus
```

With the following password file:
```txt
********
Email: john.doe@example.com
URL: https://github.com
Username: jwmwalrus
```

I get the following:
```bash
$ git pull
DEBUG:root:Received request "['protocol=https\n', 'host=github.com\n']"
DEBUG:root:Received action get with request:
{'protocol': 'https', 'host': 'github.com'}
DEBUG:root:Parsing mapping file. Command line: <_io.TextIOWrapper name='/home/jwm/.config/pass-git-helper/git-pass-mapping.ini' mode='r' encoding='UTF-8'>
DEBUG:root:Parsing command line mapping file
DEBUG:root:Received request "{'protocol': 'https', 'host': 'github.com'}"
DEBUG:root:Iterating mapping to match against host "github.com"
DEBUG:root:Section "github.com" matches requested host "github.com"
DEBUG:root:Requesting entry "dev/github.com/jwmwalrus" from pass
DEBUG:root:Received request "['protocol=https\n', 'host=github.com\n', 'username=Email: john.doe@example.com\n', 'password=********\n']"
DEBUG:root:Received action erase with request:
{'protocol': 'https', 'host': 'github.com', 'username': 'Email: john.doe@example.com', 'password': '********'}
DEBUG:root:Parsing mapping file. Command line: <_io.TextIOWrapper name='/home/jwm/.config/pass-git-helper/git-pass-mapping.ini' mode='r' encoding='UTF-8'>
DEBUG:root:Parsing command line mapping file
INFO:root:Action erase is currently not supported
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/jwmwalrus/m3u-etcetera/'
```

If, on the other hand, I try the specific line extractor (with no DEFAULT section)
```ini
[github.com]
username_extractor=specific_line
line_username=3
skip_username=10
target=dev/github.com/jwmwalrus
```

I get the following:
```bash
$ git pull
DEBUG:root:Received request "['protocol=https\n', 'host=github.com\n']"
DEBUG:root:Received action get with request:
{'protocol': 'https', 'host': 'github.com'}
DEBUG:root:Parsing mapping file. Command line: <_io.TextIOWrapper name='/home/jwm/.config/pass-git-helper/git-pass-mapping.ini' mode='r' encoding='UTF-8'>
DEBUG:root:Parsing command line mapping file
DEBUG:root:Received request "{'protocol': 'https', 'host': 'github.com'}"
DEBUG:root:Iterating mapping to match against host "github.com"
DEBUG:root:Section "github.com" matches requested host "github.com"
DEBUG:root:Requesting entry "dev/github.com/jwmwalrus" from pass
DEBUG:root:Received request "['protocol=https\n', 'host=github.com\n', 'username=n.doe@example.com\n', 'password=********\n']"
DEBUG:root:Received action erase with request:
{'protocol': 'https', 'host': 'github.com', 'username': 'n.doe@example.com', 'password': '********'}
DEBUG:root:Parsing mapping file. Command line: <_io.TextIOWrapper name='/home/jwm/.config/pass-git-helper/git-pass-mapping.ini' mode='r' encoding='UTF-8'>
DEBUG:root:Parsing command line mapping file
INFO:root:Action erase is currently not supported
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/jwmwalrus/m3u-etcetera/'
```

Modifying the password file so that the Username line is the second one, makes the helper work properly, though.

**Comment by languitar** [comment]
```
DEBUG:root:Received request "['protocol=https\n', 'host=github.com\n', 'username=Email: john.doe@example.com\n', 'password=********\n']"
```

This is the request from Git to the helper. There is already a password contained in the request. Where does that come from? Git URL in your config? Some other credential helper or keychain? And would that have been the correct password there?
