### ISSUE TITLE
Feature request: add an environment config

### ISSUE THREAD

**Issue by blockloop** [languitar/pass-git-helper#228]
Love this project by the way. I implemented my own version before I found this project, but yours is much more filled out and I like it.

However, [pass](https://git.zx2c4.com/password-store/about/#ENVIRONMENT%20VARIABLES) allows us to provide overriding environment variables. The one I've used most frequently is PASSWORD_STORE_DIR because I have a few stores that are used for different projects. 

When I'm working in project A I use PASSWORD_STORE_DIR=<myproject_dir>/.passwords to retrieve passwords for that dir.

It would be great if I could add

```
[DEFAULT]
# this isn't necessary as it's implied, but it would be nice to set this explicitly
password_store_dir=/home/blockloop/.password-store

[github.com/hello/foobar]
password_store_dir=/foo/bar/.passwords
```

I can push a PR for this because I think the main change is [here](https://github.com/languitar/pass-git-helper/blob/08d5d8547efc20df01adc395d533fd6893502def/passgithelper.py#L388) by adding the `env=<env>` flag and passing the right variables.

**Comment by blockloop** [comment]
I'm using this git config override for now:

```
[credential]
        helper = !PASSWORD_STORE_DIR=/path/to/.password-store pass-git-helper $@
```

**Comment by languitar** [comment]
What would adding the directory to the configuration offer for you that's not possible with the git configuration or something like direnv?

**Comment by blockloop** [comment]
I'm actually using direnv already. I'm keeping secrets within the project directory (e.g. PASSWORD_STORE_DIR=./.secrets) but my git credentials for upstream services are stored in my primary password store ($HOME/.password-store).

**Comment by languitar** [comment]
#240 implements the requested feature. @blockloop can you test if this works for your use case?
