### ISSUE TITLE
pypi does not have the latest version of pass-git-helper

### ISSUE THREAD

**Issue by chenrui333** [languitar/pass-git-helper#25]
👋  it looks like pypi artifact is not the latest for `pass-git-helper`

**Comment by languitar** [comment]
I somehow stopped pushing releases to pypi because I didn't see a huge requirement for a system utility to be installable in the Python packaging infrastructure. Is there a huge need for you to have this working?

**Comment by luginbash** [comment]
sorry for necromacing, but I think time has changed and now we can use `pipx` to install any cli just like brew. 

```bash
-> % pipx install pass-git-helper
  installed package pass-git-helper 0.3, installed using Python 3.12.0
  These apps are now globally available
    - pass-git-helper
done! ✨ 🌟 ✨
```
