### ISSUE TITLE
Mapping using username

### ISSUE THREAD

**Issue by mcepl** [languitar/pass-git-helper#259]
I have this in `~/.config/pass-git-helper/git-pass-mapping.ini`:

```ini
[redcrew.org:587*]
target=dev/redcrew.org:587/${username}
```

I have `~/.local/share/password-store/dev/redcrew.org:587/mcepl@cepl.eu.gpg` and but I don’t get correct result:

```sh
tumbleweed-pkg~$ echo -e 'protocol=smtp\nhost=redcrew.org:587\nusername=mcepl@cepl.eu'|git c
redential fill
DEBUG:root:Received request "['protocol=smtp\n', 'host=redcrew.org:587\n', 'username=mcepl@cepl.eu\n']"
DEBUG:root:Received action get with request:
{'protocol': 'smtp', 'host': 'redcrew.org:587', 'username': 'mcepl@cepl.eu'}
DEBUG:root:Parsing mapping file. Command line: None
DEBUG:root:Parsing mapping file None
DEBUG:root:Received request "{'protocol': 'smtp', 'host': 'redcrew.org:587', 'username': 'mcepl@cepl.eu'}"
DEBUG:root:Searching mapping to match against header "redcrew.org:587"
DEBUG:root:Section "*" matches requested header "redcrew.org:587"
DEBUG:root:Requesting entry "dev/redcrew.org:587" from pass
protocol=smtp
host=redcrew.org:587
username=mcepl@cepl.eu
password=dev/redcrew.org:587
tumbleweed-pkg~$ 
```

This is obviously not the correct password, although the correct password is on the first line of the GPG file (when I renamed `mcepl@cepl.eu.gpg` to `mceplAtcepl.eu.gpg` nothing has changed).

What’s wrong?

**Comment by languitar** [comment]
> DEBUG:root:Section "*" matches requested header "redcrew.org:587

Is there another section in the mapping with just a wildcard that triggers here?

**Comment by mcepl** [comment]
> > DEBUG:root:Section "*" matches requested header "redcrew.org:587
> 
> Is there another section in the mapping with just a wildcard that triggers here?

```
[DEFAULT]
username_extractor=specific_line
line_username=1
skip_username=7

[*]
target=dev/${host}

[github.com*]
target=dev/github

[gitlab.com*]
target=dev/gitlab

[redcrew.org:587*]
target=dev/redcrew.org:587/${username}
```

**Comment by mcepl** [comment]
Should these sections be in the other order? Does order matter?

**Comment by languitar** [comment]
You can try that. I am not sure right now if ordering counts.

**Comment by languitar** [comment]
Ah, you can also try to eliminate that wildcard section by putting the target in the default section

**Comment by mcepl** [comment]
This works:

```
[DEFAULT]
username_extractor=specific_line
line_username=1
skip_username=7

[github.com*]
target=dev/github

[gitlab.com*]
target=dev/gitlab

[redcrew.org:587*]
target=dev/redcrew.org:587/${username}

[*]
target=dev/${host}
```

But I can move `[*]` stuff put to DEFAULT, right. Anyway, I think this whole magic would be helpful if documented properly.
