### ISSUE TITLE
`wwwauth` field parsing fails on assertion

### ISSUE THREAD

**Issue by isinyaaa** [languitar/pass-git-helper#262]
`pass-git-helper` has been failing on my Arch Linux machine since I last updated my packages yesterday.

Here's the traceback with logging enabled:

```raw
DEBUG:root:Received request "['protocol=https\n', 'host=github.com\n', 'wwwauth[]=Basic realm="GitHub"\n']"
Traceback (most recent call last):
  File "/home/isinyaaa/.local/bin/pass-git-helper", line 167, in <module>
    main()
  File "/home/isinyaaa/.local/bin/pass-git-helper", line 148, in main
    request = parse_request()
              ^^^^^^^^^^^^^^^
  File "/home/isinyaaa/.local/bin/pass-git-helper", line 86, in parse_request
    assert len(parts) == 2, parts
           ^^^^^^^^^^^^^^^
AssertionError: ['wwwauth[]', 'Basic realm', '"GitHub"\n']
```

I'm using the same version of `pass` (v1.7.4), `pass-git-helper` (1.3.0, but also tried using the `-git` version from the AUR), and `git` (2.41.0) on another machine (Mac M1), with precisely the same config and no problems whatsoever.

PS: I changed the `assert` line
```diff
-assert len(parts) == 2
+assert len(parts) == 2, parts
```

**Comment by languitar** [comment]
Ah, I have never seen one of these wwwauth request entries. I can provide a quick fix for this.

**Comment by languitar** [comment]
Wait, should actually work in the most recent version. Which version of pass-git-helper are you using?

**Comment by isinyaaa** [comment]
I know what the problem is. For some reason, I have another (stale) version of `pass-git-helper` on my `.local/bin`. I've no idea how this got here, though.

I just tried deleting that file, but now I'm having another problem:

```sh
$ pass-git-helper -h
Traceback (most recent call last):
  File "/usr/bin/pass-git-helper", line 33, in <module>
    sys.exit(load_entry_point('pass-git-helper==1.3.0', 'console_scripts', 'pass-git-helper')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pass-git-helper", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^
StopIteration
```

I've already tried reinstalling the package from the AUR with no success.

Any idea what that might be? Should I open another issue?

**Comment by languitar** [comment]
you probably need to force rebuild that package if you use yay or paru to avoid re-installing a version that was built for a previous Python version. Both tools have something like `--rebuild` for that

**Comment by isinyaaa** [comment]
> you probably need to force rebuild that package if you use yay or paru to avoid re-installing a version that was built for a previous Python version. Both tools have something like `--rebuild` for that

I tried doing this but it didn't change anything.

**Comment by languitar** [comment]
What does `pacman -Ql pass-git-helper` show?

**Comment by isinyaaa** [comment]
Here

```raw
$ sudo pacman -Ql pass-git-helper
pass-git-helper /usr/
pass-git-helper /usr/bin/
pass-git-helper /usr/bin/pass-git-helper
pass-git-helper /usr/lib/
pass-git-helper /usr/lib/python3.11/
pass-git-helper /usr/lib/python3.11/site-packages/
pass-git-helper /usr/lib/python3.11/site-packages/__pycache__/
pass-git-helper /usr/lib/python3.11/site-packages/__pycache__/passgithelper.cpython-311.pyc
pass-git-helper /usr/lib/python3.11/site-packages/pass_git_helper-1.3.0-py3.11.egg-info/
pass-git-helper /usr/lib/python3.11/site-packages/pass_git_helper-1.3.0-py3.11.egg-info/PKG-INFO
pass-git-helper /usr/lib/python3.11/site-packages/pass_git_helper-1.3.0-py3.11.egg-info/SOURCES.txt
pass-git-helper /usr/lib/python3.11/site-packages/pass_git_helper-1.3.0-py3.11.egg-info/dependency_links.txt
pass-git-helper /usr/lib/python3.11/site-packages/pass_git_helper-1.3.0-py3.11.egg-info/entry_points.txt
pass-git-helper /usr/lib/python3.11/site-packages/pass_git_helper-1.3.0-py3.11.egg-info/requires.txt
pass-git-helper /usr/lib/python3.11/site-packages/pass_git_helper-1.3.0-py3.11.egg-info/top_level.txt
pass-git-helper /usr/lib/python3.11/site-packages/passgithelper.py
```

**Comment by languitar** [comment]
I can't reproduce this here. Maybe there are some more left-overs from a previous installation? Do you use some custom Python version.

**Comment by isinyaaa** [comment]
I'm using the system's python install, which makes this even more strange. I got around the problem doing `pip uninstall` after `paru -Rns` and installing from source. Seems like I really had something left behind from a previous install, but I really can't understand how this happened.
