### ISSUE TITLE
Breaks when anywhere in password file are non-UTF-8 chars

### ISSUE THREAD

**Issue by mowgli** [languitar/pass-git-helper#27]
I have many of my password files including comments and some of them uses german umlauts in latin1 encoding.

Version 0.4 included in Debian works file. But when I use the version from github, I get the following breaking:
```
Traceback (most recent call last):
  File "/home/klaus/.local/bin/pass-git-helper", line 33, in <module>
    sys.exit(load_entry_point('pass-git-helper==1.2.0.dev0', 'console_scripts', 'pass-git-helper')())
  File "/home/klaus/.local/lib/python3.9/site-packages/pass_git_helper-1.2.0.dev0-py3.9.egg/passgithelper.py", line 427, in main
  File "/home/klaus/.local/lib/python3.9/site-packages/pass_git_helper-1.2.0.dev0-py3.9.egg/passgithelper.py", line 373, in get_password
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 87: invalid start byte
```

Note, that it also happens when no configuration about username_extractor is done.

**Comment by languitar** [comment]
Interesting. I didn't think that there's still someone using something else than UTF-8... In any case, this should still work though. Switching the system to UTF-8 might still be a good idea, though ;-)

**Comment by languitar** [comment]
What is your configured locaie on your system? (`echo $LANG`)

**Comment by mowgli** [comment]
Hi Johannes,

thanks for caring about this bug. I really appreciate.

Am So den  3. Jan 2021 um 13:20 schrieb Johannes Wienke:
> What is your configured locaie on your system? (`echo $LANG`)

~> echo $LANG
de_DE
~> locale
LANG=de_DE
LANGUAGE=de_DE:en
LC_CTYPE=de_DE
LC_NUMERIC=de_DE
LC_TIME=de_DE
LC_COLLATE=de_DE
LC_MONETARY=de_DE
LC_MESSAGES=de_DE
LC_PAPER=de_DE
LC_NAME=de_DE
LC_ADDRESS=de_DE
LC_TELEPHONE=de_DE
LC_MEASUREMENT=de_DE
LC_IDENTIFICATION=de_DE
LC_ALL=

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by languitar** [comment]
Could you please run the following command and provide the output:
```
python -c "import locale; print(locale.getpreferredencoding())"
```

The problem I have here is that I somehow need to determine which text encoding is used by the encrypted entries. I could try to make this automatic with the method above in case that is sufficient for you, or an explicit option is needed. If the command above gives something in the direction of `latin1`, then your could already try the version in #28, which uses that output instead of hard-coding utf8.

**Comment by mowgli** [comment]
Hi,

Am So den  3. Jan 2021 um 13:31 schrieb Johannes Wienke:
> Could you please run the following command and provide the output:
> ```
> python -c "import locale; print(locale.getpreferredencoding())"
> ```

~> python -c "import locale; print(locale.getpreferredencoding())"
ISO-8859-1

That is the default encoding if not specified in LC_* environments. And
it is my correct encoding.

> The problem I have here is that I somehow need to determine which text encoding is used by the encrypted entries. I could try to make this automatic with the method above in case that is sufficient for you, or an explicit option is needed. If the command above gives something in the direction of `latin1`, then your could already try the version in #28, which uses that output instead of hard-coding utf8.

The troubles with UTF-8 as encoding is, that UTF-8 is not able to
represent every byte value. latin1 is as most 8bit encodings are.

As that solution will work for me, I think, it is a bit to narrow
thought. What if someone set the encoding in his shell to UTF-8 but have
files encoded in latin1? vim will handle that pretty fine but in that
case, it will fail in pass-git-helper the same way as before.

Solution could be to default to the console encoding but allow to:
1. configure the encoding
2. detect the encoding. It could be pretty easy to try open in UTF-8 and
   if that fails, open in a 8bit encoding.

Regards
   Klaus

Ps. Currently I have to fight the common python trouble "AttributeError:
    'zipimporter' object has no attribute 'find_spec'" when trying to
    install the tool. It happens since system update yesterday.
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by mowgli** [comment]
Hi,

I found the trouble with zipimporter. If I have run `python3 setup.py
install --user` run once, I am not able to run it again anymore. I have
to delete ~/.local/lib/python3.9 and then it is working again (but only
once).

It has also side effects to other tools like vim taskwiki.

Really strange as your software has no mention to zipimporter and I am
not able to find any definition of that object in the whole python
installation. But I found some random bugs in different python software
about that error.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by languitar** [comment]
Regarding your installation issues:

Installing with `--user` is always potentially dangerous because the `~/.local` is always added to the pythonpath. If you install some package with pip, it might potentially place newer versions of dependencies in this path that might for instance conflict with python packages installed using your Linux package manager. I would try to avoid `--user` and the `~/.local` path for these reasons. Instead, installing in a virtualenv is usually the better option. In case of the simple script in this project, copying it to `/usr/local/bin` is also an option.

Regarding the actual encoding issues:

I have to pass the extracted password to git using the text format described in [`git-credential`](https://git-scm.com/docs/git-credential). Unfortunately, the documentation there is pretty sparse on how encoding is handled. I would suspect that git uses what is configured via the `LANG` and `LC_*` but that's only a guess. In that case, simply using any 8bit encoding would probably result in broken special characters if the file and the system encoding do not agree. Therefore, configuring the file encoding is probably the only option.

**Comment by mowgli** [comment]
Hi Johannes,

Am So den  3. Jan 2021 um 16:27 schrieb Johannes Wienke:
> Regarding your installation issues:
> 
> Installing with `--user` is always potentially dangerous ...

Well, sure but it should not break many python tools just after the
intsallation.

I found the problem and created a python bug report issue42818
(https://bugs.python.org/issue42818). It is _NOT_ in your tool.

The problem is, that the egg file is zipped and the zipimport(er) class
is broken since several versions of python when they move from
find_loader to find_spec.

When I install the tool with `python3 setup.py install --user
--old-and-unmanageable`, it work fine. So this "old-and-unmanageable"
make it managable at all.

> In case of the simple script in this project, copying it to `/usr/local/bin` is also an option.

Ah, I didn't know that this is possible. I like that much more than to
install it in user folder.

> Regarding the actual encoding issues:
> 
> I have to pass the extracted password to git using the text format described in [`git-credential`](https://git-scm.com/docs/git-credential). Unfortunately, the documentation there is pretty sparse on how encoding is handled. I would suspect that git uses what is configured via the `LANG` and `LC_*` but that's only a guess. In that case, simply using any 8bit encoding would probably result in broken special characters if the file and the system encoding do not agree. Therefore, configuring the file encoding is probably the only option.

Good point.

I think, git is just agnostic for encoding and just transfer bytes.
Maybe it is best to forward them the same encoding as it is in the pass
file. That would even allow to have binary password.

However, maybe there are other use cases where the encoding differs
between file and locale. I don't know.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by languitar** [comment]
> I think, git is just agnostic for encoding and just transfer bytes. Maybe it is best to forward them the same encoding as it is in the pass file. That would even allow to have binary password.

I just tested the assumption above and git decodes the input of the credential helper with the locale configured using the respective environment variables. It has to know the password text to provide it in the required form to basic auth. Therefore, simply forwarding the raw byte sequence without decoding it to proper text won't work. I will add an encoding option as guessing is also error-prone.

**Comment by languitar** [comment]
Alright, the branch is updated to a version with configurable encoding. Would you mind testing that version?

**Comment by languitar** [comment]
#29 now also contains updated installation instructions reflecting the discussions here.

**Comment by mowgli** [comment]
Am So den  3. Jan 2021 um 17:26 schrieb Johannes Wienke:
> Alright, the branch is updated to a version with configurable encoding. Would you mind testing that version?

Works perfect.

Tested it once without encoding configuration (which fails expectable)
and then with it which made it work.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by languitar** [comment]
Great, thanks for the immediate feedback.
