### ISSUE TITLE
Using more than one capture group in regex_username

### ISSUE THREAD

**Issue by stefanct** [languitar/pass-git-helper#292]
Hi,
I had a number of different "field" names in my pass db corresponding to the user ID of the respective accounts. To match them all I would have had to use a few additional parentheses in my regex which currently does not work, e.g., `^(user(name)?|login): *(.*)$` doesn't work because the [script is hard-coded to use the first capture group](https://github.com/languitar/pass-git-helper/blob/6239fc8ab1c1d7042b31da68098e035e8a2fc143/passgithelper.py#L291). The config value is also checked beforehand to not allow execution and warn the user and the limitation is also documented in the README (thumbs up :)

I changed my pass entries so this is no immediate issue for me at all. However, I wonder if the situation could be improved. The most obvious thing would be to not hard-code `1` but simply use the last capture group. I'd assume this would fix most use cases already. A more sophisticated solution could be another configuration value that specifies which capture group to use. What do you think?

**Comment by languitar** [comment]
Python regular expressions have support for non-capturing parentheses:

> (?:...)
>
> A non-capturing version of regular parentheses. Matches whatever regular expression is inside the parentheses, but the substring matched by the group cannot be retrieved after performing a match or referenced later in the pattern.

https://docs.python.org/3/library/re.html#regular-expression-syntax

Does that work in your case?

**Comment by stefanct** [comment]
Thank you. I haven't tested it but I would presume that this should make above RE work?  `^(?:user(??name)?|login): *(.*)$`
Maybe we want to add something about that to the readme? Feel free to close this ticket in any case.

**Comment by languitar** [comment]
> Thank you. I haven't tested it but I would presume that this should make above RE work? `^(?:user(??name)?|login): *(.*)$` 

Why the double question mark? Otherwise, this might work.

> Maybe we want to add something about that to the readme? Feel free to close this ticket in any case.

I'll prepare something.

**Comment by stefanct** [comment]
I think I meant to type `:?` instead of `??` and didn't check apparently. Thanks for the change! Bye
