### ISSUE TITLE
[Request] Support for “canonical” and QtPass --multiline organization

### ISSUE THREAD

**Issue by Celti** [languitar/pass-git-helper#4]
Both the pseudo-canonical format for usernames suggested by the author of `pass` [("Username: name")](https://www.passwordstore.org/#organization) and the format used by [QtPass](https://qtpass.org/) and [PassFF](https://github.com/jvenant/passff) ("login:name") break pass-git-helper's attempt at reading the username.

It would be nice if pass-git-helper could accept usernames in these formats — heuristically would be fantastic, configurably still very nice and likely much easier — perhaps a section-zero entry in git-pass-mappng.ini, "prefix = ", defining a prefix to remove from the second line of the password file to turn it into a username?

**Comment by languitar** [comment]
The format of the entries really lacks structure. And suddenly so many different conventions emerge. :/ However, adding an option to replace certain prefixes would be possible. I just need to find the time to do that.
