### ISSUE TITLE
stopped working on arch after adoption of python 3.10

### ISSUE THREAD

**Issue by isinyaaa** [languitar/pass-git-helper#41]
Using pyenv, one can see that `pass-git-helper` won't really install on 3.10
```raw
pyenv: pass-git-helper: command not found

The `pass-git-helper' command exists in these Python versions:
  3.9.9

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

Edit:
It does work flawlessly when you install it using `setup.py` (instead of using the AUR). So maybe close this issue and update the `PKGBUILD`?

**Comment by languitar** [comment]
This is fixed However, the packaging for Arch isn't maintained in this repository.
