### ISSUE TITLE
feature request: introduce option to chose alternate 'pass' command

### ISSUE THREAD

**Issue by ehaupt** [languitar/pass-git-helper#43]
**Background:**

There are some popular forks of `pass` such as [gopass](https://github.com/gopasspw/gopass) that are command compatible. It would be nice if the user could chose the `pass` command either via command-line option or a configure parameter.

**Idea:**

Introduce a command-line option (maybe `--pass-cmd`) or a parameter for the `*.ini` file.

**Sample usage:**

```sh
usage: pass-git-helper [-h] [-m MAPPING_FILE] [-l] [--pass-cmd PASS_CMD] ACTION

Git credential helper using pass as the data source.

positional arguments:
  ACTION                Action to preform as specified in the git credential API

optional arguments:
  -h, --help            show this help message and exit
  -m MAPPING_FILE, --mapping MAPPING_FILE
                        A mapping file to be used, specifying how hosts map to pass entries. Overrides the default mapping files from XDG config locations, usually:
                        /home/ehaupt/.config/pass-git-helper/git-pass-mapping.ini (default: None)
  -l, --logging         Print debug messages on stderr. Might include sensitive information (default: False)
  --pass-cmd PASS_CMD   Pass command (default: pass)
```

**Comment by languitar** [comment]
I think the command line version better fits the current design. The ini file is only used for defining the mappings so far.

Are you able to contribute a PR for this? Shouldn't be to hard to implement.

**Comment by ehaupt** [comment]
> I think the command line version better fits the current design. The ini file is only used for defining the mappings so far.

I agree.

> Are you able to contribute a PR for this? Shouldn't be to hard to implement.

Sure, I'll follow up with a PR.

**Comment by ehaupt** [comment]
Hello @languitar, sorry got sidetracked. I've been using https://github.com/gopasspw/git-credential-gopass instead. It's specially made for `gopass`. Please feel free to close.
